import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const queryClient = new QueryClient()

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full font-sans">
      <body className={inter.className + " h-full bg-gray-100 leading-tight"}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html >
  )
}
