name: Check for new master data

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  check_new_master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run script
        run: |
          chmod +x ./scripts/check-for-new-master-data.sh
          ./scripts/check-for-new-master-data.sh
