name: Check for new master data

on:
  # every hour between 8:00 and 20:00 JST
  schedule:
    - cron: "0 23-23 * * *"
    - cron: "0 0-11 * * *"
  workflow_dispatch:

jobs:
  check_new_master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run script
        run: |
          chmod +x ./scripts/check-for-new-master-data.sh
          ./scripts/check-for-new-master-data.sh
