name: Check for new master data

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  check_new_master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run script
        run: |
          chmod +x check_new_master.sh
          ./check_new_master.sh
